### PR TITLE
Bugs in filesapp

### LINKED ISSUE #217: iPhone SE files list scrolls to high after refresh
Hi, 

After the last update the issue appeared in the file browser. 

After opening the app file browser screen is fine, but after pulling the list and refreshing content it goes too high, so the first folder is partially overlapped.

I found that in a simulator (also SE) there is a search field added (on my real device I did not). So in case of a simulator scroll view scroll almost to hide the search bar, in case of a real device it provides a bug.

The first screen is initial state, and the second one is after refresh.
fullsizerender 2
fullsizerender

P.S. I assume the problem is about on my device search field is somehow missed.

iPhone SE
iOS 10.3.2
Version 2.7.7

Best regards,
Maks

### PR DESCRIPTION
**Pull request by lilthree**
1.fix file shows size 0KB and date 1.1.1970
2.fix tagged file don’t appear in files.app
3.add refresh when folder in the files.app is empty.
4.fix #217

### CODE REVIEW

File: SeafFileProvider/FileProvider.m [hunk 1]
```diff
@@ -15,15 +15,20 @@
 #import "ExtentedString.h"
 #import "Utils.h"
 #import "Debug.h"
+#import "NSError+SeafFileProvierError.h"
+#import "SeafStorage.h"
 
 @interface FileProvider ()
+@property (nonatomic, assign) NSInteger currentAnchor;
```
Comment (poetwang) [inline SeafFileProvider/FileProvider.m]: where does currentAnchor get initialized?
